[theme]
primaryColor = "#00C2CB"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#15324D"
textColor = "#E6EDF3"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
